joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

panthera_controller:
  type: "panthera_controller/PantheraController"
  front_wheel: ['fl_wheel_link_joint', 'fr_wheel_link_joint']
  rear_wheel: ['rl_wheel_link_joint', 'rr_wheel_link_joint']
  front_steering: ['fl_steering_link_joint', 'fr_steering_link_joint']
  rear_steering: ['rl_steering_link_joint', 'rr_steering_link_joint']
  reconfiguration: ['base_left_joint', 'base_right_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.5
  wheel_radius : 0.1
  track_width : 0.7 # distance between left and right wheels (in fully compressed state)
  wheel_base : 1.308
  base_frame_id: base_footprint
  odom_frame_id: odom
  state_frame_id: state # n-dimensional state of the reconfigurable robot

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: true

/gazebo_ros_control:
  pid_gains:
    base_left_joint:
      p: 50
      i: 0.01
      d: 10
    base_right_joint:
      p: 50
      i: 0.01
      d: 10
    fl_steering_link_joint:
      p: 50
      i: 1
      d: 0.01
    fr_steering_link_joint:
      p: 50
      i: 1
      d: 0.01
    rl_steering_link_joint:
      p: 50
      i: 1
      d: 0.01
    rr_steering_link_joint:
      p: 50
      i: 1
      d: 0.01
    fl_wheel_link_joint:
      p: 10
      i: 1
      d: 0.01
    fr_wheel_link_joint:
      p: 10
      i: 1
      d: 0.01
    rl_wheel_link_joint:
      p: 10
      i: 1
      d: 0.01
    rr_wheel_link_joint:
      p: 10
      i: 1
      d: 0.01